### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by btford** [btford/ngmin#4]

**Comment by ffesseler** [comment]
I'm having some difficulties launching tests.
I've checkout the last version, did `npm install` and installed globally mocha.

When I type `mocha` from the root directory, all tests fail with the same error : 

```
29) annotate should not annotate values:                                                                    
   Error: Line 1: Unexpected token (                                                                        
    at throwError (C:\Users\tuser\Temp\ngmin\node_modules\esprima\esprima.js:1156:21)                   
    at throwUnexpected (C:\Users\tuser\Temp\ngmin\node_modules\esprima\esprima.js:1213:9)               
    at parseVariableIdentifier (C:\Users\tuser\Temp\ngmin\node_modules\esprima\esprima.js:2082:13)      
    at parseFunctionDeclaration (C:\Users\tuser\Temp\ngmin\node_modules\esprima\esprima.js:2884:14)     
    at parseSourceElement (C:\Users\tuser\Temp\ngmin\node_modules\esprima\esprima.js:3055:24)           
    at parseSourceElements (C:\Users\tuser\Temp\ngmin\node_modules\esprima\esprima.js:3095:29)          
    at parseProgram (C:\Users\tuser\Temp\ngmin\node_modules\esprima\esprima.js:3109:19)                 
    at Object.parse (C:\Users\tuser\Temp\ngmin\node_modules\esprima\esprima.js:3856:23)                 
    at exports.stringifyFunctionBody (C:\Users\tuser\Temp\ngmin\test\util.js:22:13)                     
    at annotate (C:\Users\tuser\Temp\ngmin\test\simple.js:14:5)                                         
    at Context.<anonymous> (C:\Users\tuser\Temp\ngmin\test\simple.js:240:21)                            
    at Test.Runnable.run (C:\Users\tuser\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:213:32) 
    at Runner.runTest (C:\Users\tuser\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:10)      
    at Runner.runTests.next (C:\Users\tuser\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:397:12)
    at next (C:\Users\tuser\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:277:14)                
    at Runner.hooks (C:\Users\tuser\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:286:7)         
    at next (C:\Users\tuser\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:234:23)                
    at Runner.hook (C:\Users\tuser\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:254:5)          
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)                                
```

**Comment by btford** [comment]
I cannot reproduce. Seems like it might be a Windows issue.

**Comment by ffesseler** [comment]
Any idea how I could resolve this ?

I'd like to try fixing #35. 
(IMO, any non trivial app will use at least one resolve...)
